### ISSUE TITLE
Panamera S Sound

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#1103] opened 2022-05-26 03:56 UTC
Is there anyway you can change the sound of the Panamera Turbo S, I found a nice sound pack for it that I would like to be put in, instead of the current one. 
https://www.gta5-mods.com/vehicles/vw-audi-4-0t-v8-ea825-engine-sound-oiv-addon-fivem

**Comment by TdotG** [comment] 2022-05-26 09:30
Also can you please fix the dirtmap

**Comment by fkk-cz** [comment] 2022-05-26 09:35
There is no 'fix' for a dirtmap texture. The vehicle creator decided to add the dirtmapping texture, this is not an issue caused by us when the vehicle was added or converted. Changing `dirtLevelMax` seems to have no effect either. @No-Yes1 

Not sure whether deleting the texture would even work, as that could cause visual issues with the vehicle.

**Comment by TdotG** [comment] 2022-05-26 10:16
Appreciate it, also can the sound pack be changed to the one that I found? Would really appreciate it.

**Comment by No-Yes1** [comment] 2022-05-26 20:02
> There is no 'fix' for a dirtmap texture. The vehicle creator decided to add the dirtmapping texture, this is not an issue caused by us when the vehicle was added or converted. Changing `dirtLevelMax` seems to have no effect either. @No-Yes1
> 
> Not sure whether deleting the texture would even work, as that could cause visual issues with the vehicle.

Damn, alright

**Comment by TdotG** [comment] 2022-05-26 20:05
That’s fine, would you be able to put the Urus’ audio file instead then?

**Comment by TdotG** [comment] 2022-05-26 20:13
Scratch that, if you can do that AMG GT black series sound that would be greatly appreciated.

**Comment by PsychoticCore** [comment] 2022-05-26 20:18
> Scratch that, if you can do that AMG GT black series sound that would be greatly appreciated.

I know I have no word in this decision but I think that'd be quite unrealistic 😂 complete different cars & manufacturer with different engines and everything in it they're both V8 but

**Comment by TdotG** [comment] 2022-05-26 20:22
Only reason I’m saying that one is because it has the best sounding v8 so why not lol.

**Comment by TdotG** [comment] 2022-05-28 08:51
So lmk if you could do the AMG GT Black Series audio file on the car

**Comment by No-Yes1** [comment] 2022-05-29 13:00
Tweaked to the ``urus2018`` sound as that is more better/realistically sounding https://github.com/fkk-cz/noire_vehicles/commit/d36462bbe84d9caf73909eea59f06f8d0de78f12. Please wait until this is merged.

**Closed by No-Yes1** 2022-05-29 13:00 UTC
