### ISSUE TITLE
Dodge Charger Hellcat makes screen bug.

### ISSUE THREAD

**Issue by Rakeem21** [fkk-cz/noire_vehicles#1324] opened 2022-08-09 23:13 UTC
When I am in the hellcat with my friend, it makes my screen start glitching out and i just get a glitchy screen where it just turns my screen black and back to normal very quickly but it is really annoying it keeps happening to me and also to my friends screen, and to everyone else that hops in it.

**Comment by Rakeem21** [comment] 2022-08-09 23:29
correction, it repeatedly turns part of my screen black and back to normal very quickly until i get out of the car.

**Comment by fkk-cz** [comment] 2022-08-10 05:06
Duplicate of #1320.

**Closed by fkk-cz** 2022-08-10 05:06 UTC
Labels: duplicate
