### ISSUE TITLE
Mercedes e-63 bugged

### ISSUE THREAD

**Issue by Dallasknight** [fkk-cz/noire_vehicles#1183] opened 2022-06-27 04:07 UTC
Anytime my friends and i got into the car we all would crash. We tried someone else’s Mercedes and it did the same thing after driving for a bit. I crashed a total of 4 times in 10 minutes. When we would ride in a different car we would be fine. But just being around the car or riding in it, it would cause multiple people to crash at the same time.

**Comment by No-Yes1** [comment] 2022-06-27 04:23
Duplicate of an already made issue https://github.com/fkk-cz/noire_vehicles/issues/1180

**Closed by No-Yes1** 2022-06-27 04:23 UTC
