### ISSUE TITLE
Nissan Silvia S14

### ISSUE THREAD

**Issue by FukBerk** [fkk-cz/noire_vehicles#1269] opened 2022-07-23 16:02 UTC
all of the mods disappeared on this car, I had it fulled modded out and when I pulled the car out of my garage today it was back to bone stock like how it is from PDM. Options are not in the mod shop to modify it anymore either

**Comment by okxeon** [comment] 2022-07-23 17:49
I probably duplicated its modkit on accident. Will take a look in a few here.

**Comment by FukBerk** [comment] 2022-07-23 22:38
thank you!

**Comment by okxeon** [comment] 2022-07-24 22:57
Fixed here https://github.com/fkk-cz/noire_vehicles/commit/d0a70d543158fd0cb742360c4fef55266feda03e. Issue was caused by a duplicate modkit ID from adding additional cars. Once merged car should al ay okay.

**Closed by okxeon** 2022-07-24 22:57 UTC
Labels: no upgrades
